//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterIndication
    {
        public int IndicationId { get; set; }
        public int AccountKey { get; set; }
        public int CounterKey { get; set; }
        public string Measure { get; set; }
        public int Value { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Counter Counter { get; set; }
    }
}
