//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DI
{
    using System;
    using System.Collections.Generic;
    
    public partial class communication
    {
        public int id { get; set; }
        public int field_id { get; set; }
        public string value { get; set; }
        public int company_id { get; set; }
    }
}
