SET IDENTITY_INSERT [dbo].[communication] ON
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (1, 1, N'125', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (2, 2, N'140', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (3, 3, N'15', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (4, 4, N'2', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (5, 5, N'0,3', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (6, 6, N'85', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (7, 7, N'2', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (8, 8, N'33', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (9, 9, N'0,625', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (10, 10, N'0,07', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (11, 11, N'4', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (12, 12, N'2', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (13, 13, N'1,2', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (14, 14, N'3', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (15, 15, N'131', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (16, 16, N'80', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (17, 17, N'0,3', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (18, 18, N'98,5', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (19, 19, N'0', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (20, 20, N'0', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (21, 21, N'0', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (22, 22, N'0', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (23, 23, N'0', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (24, 24, N'0', 1)
INSERT INTO [dbo].[communication] ([id], [field_id], [value], [company_id]) VALUES (25, 25, N'0', 1)
SET IDENTITY_INSERT [dbo].[communication] OFF
