SET IDENTITY_INSERT [dbo].[fields] ON
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (1, N'q', N'Расход сточных вод', N'м^3 / ч')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (2, N'L_ln', N'Практически полное окисление(БПКполн) воды поступающей в аэротенк', N'мг / л')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (3, N'L_ex', N'Практически полное окисление(БПКполн) очищенной сточной воды', N'мг / л')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (4, N'a', N'Доза активного ила', N'г / л')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (5, N'S', N'Зольность ила', N'безразмерн.')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (6, N'p_max', N'Максимальная удельная скорость окисления органических загрязнений', N'мг БПКполн / г*ч')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (7, N'C_0', N'Концентрация растворенного кислорода', N'мг / л')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (8, N'K_l', N'Константа, характеризующая свойства органических загрязняющих веществ', N'мг БПКполн / л')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (9, N'K_0', N'Константа, характеризующая влияние кислорода', N'мг БПКполн / л')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (10, N'phee', N'Коэффициент ингибирования биологических процессов продуктами распада активного ила', N'л / г')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (11, N'n_at', N'Число секций в аэротенке', N'безразмерн.')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (12, N'n_cor', N'Число коридоров в секции аэротенка', N'безразмерн.')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (13, N'H_at', N'Рабочая глубина аэротенка', N'м')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (14, N'b_cor', N'Ширина коридора в аэротенке', N'м')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (15, N'W_i', N'Рабочий объем одной секции', N'м^3')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (16, N'C_cdp', N'Концентрация взвешенных веществ, поступивших в аэротенк', N'мг / л')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (17, N'K_g', N'Коэффициент прироста активного ила', N'безразмерн.')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (18, N'J_i', N'Иловый индекс', N'см^3 / г')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (19, N'p', N'Удельная скорость окисления загрязнений', N'мг БПКполн / г*ч')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (20, N't_atm', N'Длительность аэрации в аэротенке', N'ч')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (21, N'q_i', N'Нагрузка на активный ил', N'мг БПКполн / г*сут')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (22, N'R_i', N'Степень рециркуляции активного ила', N'безразмерн.')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (23, N'W_atm', N'Объем аэротенка', N'м^3')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (24, N'L_at', N'Длина аэротенка', N'м')
INSERT INTO [dbo].[fields] ([id], [name], [description], [measure]) VALUES (25, N'P_i', N'Прирост активного ила', N'мг / л')
SET IDENTITY_INSERT [dbo].[fields] OFF
